version: '3.8'

services:
  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}
    container_name: job-ai-reply-bot
    ports:
      - "5000:5000" # HTTP
      - "8443:8443" # HTTPS
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:8443
      - Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - Kestrel__Certificates__Default__Path=/app/localhost.pfx
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - TelegramBotToken=${TELEGRAM_BOT_TOKEN}
      - AuthorChatId=${AUTHOR_CHAT_ID}
      - ChatGptAccessToken=${CHAT_GPT_ACCESS_TOKEN}
    volumes:
      - ./localhost.pfx:/app/localhost.pfx:ro
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: job-ai-reply-db
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network

volumes:
  mssql_data:

networks:
  app_network:
