name: CI/CD for JobAIReplyBot

on:
  push:
    branches:
      - main
      - feature/setup-ci-cd
  pull_request:
    branches:
      - main

env:
  REGISTRY: registry.digitalocean.com/job-ai-reply-bot
  IMAGE_NAME: job-ai-reply-bot
  CONTAINER_NAME: job-ai-reply-bot
  ENV_FILE_PATH: .env
  LOGS_PATH: /root/job-ai-reply-bot/logs



jobs:
#  build_and_test:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 8.0.x
#
#      - name: Install dependencies
#        run: dotnet restore
#
#      - name: Build
#        run: dotnet build --no-restore
#
#      - name: Test
#        run: dotnet test --no-build --verbosity normal
  
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
#    needs: build_and_test

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Build container image
        run: |
          docker build -f src/DjinniAIReplyBot.Api/Dockerfile -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
   
  copy_files:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose.prod.yml to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "/root/job-ai-reply-bot/"

  deploy:
    runs-on: ubuntu-latest
    needs: copy_files
    
    steps:
      - name: Deploy to DigitalOcean droplet via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REGISTRY,IMAGE_NAME,GITHUB_SHA,DEFAULT_CONNECTION,TELEGRAM_BOT_TOKEN,AUTHOR_CHAT_ID,CHAT_GPT_ACCESS_TOKEN,SA_PASSWORD
          script: |
            # Login to Docker Registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} $REGISTRY
            
            # Перейти до директорії з docker-compose.yml
            cd /root/job-ai-reply-bot
            
            # Створити файл .env з необхідними змінними
            echo "ConnectionStrings__DefaultConnection=${{ secrets.DEFAULT_CONNECTION }}" > $ENV_FILE_PATH
            echo "TelegramBotToken=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $ENV_FILE_PATH
            echo "AuthorChatId=${{ secrets.AUTHOR_CHAT_ID }}" >> $ENV_FILE_PATH
            echo "ChatGptAccessToken=${{ secrets.CHAT_GPT_ACCESS_TOKEN }}" >> $ENV_FILE_PATH
            echo "SA_PASSWORD=${{ secrets.SA_PASSWORD }}" >> $ENV_FILE_PATH
            echo "REGISTRY=${REGISTRY}" >> $ENV_FILE_PATH
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $ENV_FILE_PATH
            echo "GITHUB_SHA=${{ github.sha }}" >> $ENV_FILE_PATH
            
            # Stop and remove old containers
            docker-compose -f docker-compose.prod.yml down || true
            
            # Pull the latest image
            docker-compose -f docker-compose.prod.yml pull
            
            # Start services with Docker Compose
            docker-compose -f docker-compose.prod.yml up -d
          debug: true

